import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import { Providers } from './Providers'
import Contact from '@/components/Contact'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'AF Travel',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='light'>
      <body className={inter.className}>
        <Providers>
          {/* <Navbar /> */}
          {children}
          {/* <Contact/>
          <Footer /> */}
        </Providers>
      </body>
      {/* <script src="../path/to/flowbite/dist/flowbite.min.js"></script> */}
    </html>
  )
}
